spring:
  mail:
    host: smtp.qq.com
    username: ENC(pcwk0OeluFhpizIVvxYTR5O+K25C3n89WSnHwijluDSMqXO+xeSEBB2wEJZ6heJ2)
    password: ENC(v6vNaa+Iabtt+Ji/6WzYQ+vjALohF12JBR/hGYSslJtwuHUJ3YpnRgYdkggxy7G8)
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

#jasypt:
#  encryptor:
#    password: test
